basePath: /api
definitions:
  golang-rest-api-template_internal_handlers_category_model.CategoryByIDResponse:
    properties:
      data:
        $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.CategoryDetail'
      message:
        type: string
      success:
        type: boolean
    type: object
  golang-rest-api-template_internal_handlers_category_model.CategoryDetail:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
    type: object
  golang-rest-api-template_internal_handlers_category_model.CreateCategoryRequest:
    properties:
      description:
        type: string
      name:
        type: string
      parent_id:
        type: integer
    required:
    - description
    - name
    - parent_id
    type: object
  golang-rest-api-template_internal_handlers_category_model.CreateCategoryResponse:
    properties:
      data:
        properties:
          category_id:
            type: integer
        type: object
      message:
        type: string
      success:
        type: boolean
    type: object
  golang-rest-api-template_internal_handlers_category_model.StandardResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  golang-rest-api-template_internal_handlers_category_model.UpdateCategoryRequest:
    properties:
      description:
        type: string
      name:
        type: string
      parent_id:
        type: integer
    required:
    - description
    - name
    - parent_id
    type: object
  golang-rest-api-template_internal_handlers_product_model.CreateProductRequest:
    properties:
      category_id:
        type: integer
      description:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    required:
    - category_id
    - description
    - name
    - price
    - stock
    type: object
  golang-rest-api-template_internal_handlers_product_model.ProductDetailResponse:
    properties:
      category_id:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  golang-rest-api-template_internal_handlers_product_model.StandardResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  golang-rest-api-template_internal_handlers_product_model.UpdateProductRequest:
    properties:
      category_id:
        type: integer
      description:
        type: string
      name:
        type: string
      price:
        minimum: 1
        type: number
      stock:
        type: integer
    required:
    - category_id
    - description
    - name
    - price
    - stock
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: REST API Template Example
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - HealthCheck
  /v1/category/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Category example
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
      summary: Delete Category example
      tags:
      - Category
    get:
      consumes:
      - application/json
      description: Get Category details example
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.CategoryByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
      summary: Get Category details example
      tags:
      - Category
    put:
      consumes:
      - application/json
      description: Update Category example
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
      summary: Update Category example
      tags:
      - Category
  /v1/create-category:
    post:
      consumes:
      - application/json
      description: Create Category example
      parameters:
      - description: Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.CreateCategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_category_model.StandardResponse'
      summary: Create Category example
      tags:
      - Category
  /v1/create-product:
    post:
      consumes:
      - application/json
      description: Create Product example
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.ProductDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
      summary: Create Product example
      tags:
      - Product
  /v1/product/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Product example
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
      summary: Delete Product example
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: Get Product details example
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.ProductDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
      summary: Get Product details example
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Update Product example
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/golang-rest-api-template_internal_handlers_product_model.StandardResponse'
      summary: Update Product example
      tags:
      - Product
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
