basePath: /api
definitions:
  model.CreateProductRequest:
    properties:
      category_id:
        type: integer
      description:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    required:
    - category_id
    - description
    - name
    - price
    - stock
    type: object
  model.ProductDetailResponse:
    properties:
      category_id:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  model.StandardResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  model.UpdateProductRequest:
    properties:
      category_id:
        type: integer
      description:
        type: string
      name:
        type: string
      price:
        minimum: 1
        type: number
      stock:
        type: integer
    required:
    - category_id
    - description
    - name
    - price
    - stock
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: REST API Template Example
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - HealthCheck
  /v1/create-product:
    post:
      consumes:
      - application/json
      description: Create Product example
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProductDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.StandardResponse'
      summary: Create Product example
      tags:
      - Product
  /v1/product/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Product example
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.StandardResponse'
      summary: Delete Product example
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: Get Product details example
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProductDetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.StandardResponse'
      summary: Get Product details example
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Update Product example
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.StandardResponse'
        "404":
          description: 404 page not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.StandardResponse'
      summary: Update Product example
      tags:
      - Product
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
